version: '3.8'
services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password123
    ports:
      - "1434:1433"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
